### ISSUE TITLE
Getting it working.

### ISSUE THREAD

**Issue by Croella** [AdrianCassar/Xenia-WebServices#26]
Hello I'm sorry if this isn't how I'm supposed to contact you, I was just curious how I would get the Black Ops II beta to work with a friend. I've hosted a server locally and everything, It just seems we can't connect to online, and system link doesn't show either of us. I also noticed the servers don't show on 127.0.0.1:3600 when I host it in system link. I'm just unsure how to get it working properly. Any answer is appreciated, again sorry if this isn't the location for this !

**Comment by AdrianCassar** [comment]
CODs in general require a custom server for xbox live so yes you cannot connect online. Systemlink should work for most CODs using **Radmin VPN** as systemlink only works on the same network. The API address `127.0.0.1` should never be used, it's a placeholder.

Support is usually handled in the discord server.

**Comment by Croella** [comment]
alright, thank you i appreciate it. I couldn't find a discord server, perhaps I didn't look hard enough.
