### ISSUE TITLE
Network access passthrough?

### ISSUE THREAD

**Issue by kamil00110** [AdrianCassar/Xenia-WebServices#34]
Its not quite an issiue it is more a question.
Im doing a little of homebrew with xenia-netplay and i try to acces the normal network from my game. I should have enabled Xbox Live security Bypass for my game. But i still cant acces the normal network and there is the question: Is some network access passthrough not implemented or could it be my programms fault. 
If some more detail are needed then i can provide it and when its not inplemented could it be done?

**Comment by kamil00110** [comment]
I mean if the api also handels external web requests that could be used for accesing external network resources.

**Comment by AdrianCassar** [comment]
If you want your game to access a XLSP server then you can configure it using `servers.json`. Halo 3 for example [servers.json](https://github.com/AdrianCassar/Xenia-WebServices/blob/main/titles/4D5307E6/servers.json).

If the game itself performs XHttp requests to external servers or title storage this isn't supported. However, you can try using the HINTERNET branch [https://github.com/AdrianCassar/xenia-canary/pull/36](https://github.com/AdrianCassar/xenia-canary/pull/36)https://github.com/AdrianCassar/xenia-canary/pull/36 which implements XHttp functions however it's incomplete.

**Comment by kamil00110** [comment]
Thank im
