### ISSUE TITLE
trouble building web services

### ISSUE THREAD

**Issue by judofright** [AdrianCassar/Xenia-WebServices#40]
Ive been following the directions but have had some issues.  MongoDB compass shows xbox live reborn but it wont start, but when i try to build i get a massive amount of errors saying swagger and bunch of other stuff saying "can't find module".  would love to get this working but maybe i should wait till its more simplified.

`Cannot find module '@nestjs/core' or its corresponding type declarations.`  says this like a thousand times on a bunch of different modules.

edit: correction i fixed it by install a missing module.  but now i cant get the server to connect to the mongodb & mongo compass keeps saying cant connect, read ECONNRESET.  I have no idea how to make a ssl certificate so...

**Comment by AdrianCassar** [comment]
You can find a .env template [here](https://github.com/AdrianCassar/Xenia-WebServices/blob/main/.env.template).
